[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false

[package]
name = "raytracer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
